# Generated by Django 6.0.7 on 2026-07-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=20)),
                ('source_type', models.CharField(choices=[('B2B', 'B2B'), ('B2C', 'B2C')], max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='clients.client')),
            ],
        ),
    ]
