import gzip
from io import StringIO

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.mail import EmailMessage
from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.utils import timezone


class Command(BaseCommand):
    help = (
        'Email every staff account with an email on file a full gzipped database '
        'backup (Django dumpdata, generated in-process — no pg_dump or other external '
        "tooling needed). Nothing in this project runs on a schedule by itself; point "
        'a scheduler (Render Cron Job / cron / Windows Task Scheduler) at this command. '
        'Unlike send_admin_digest/auto_archive_completed_students, this always sends '
        'mail when it runs, so a weekly schedule is more sensible than daily.'
    )

    # Auto-regenerated by migrations (contenttypes, auth.permission), zero backup
    # value (sessions), or live credentials that shouldn't sit in an email attachment
    # indefinitely (config.authtoken — one row per logged-in device, see AuthToken's
    # docstring; authtoken.token is the older, now-unused model kept only so its table
    # isn't dropped) — restoring any of these from an old dump would be actively
    # wrong, not just unnecessary.
    EXCLUDED_MODELS = ['contenttypes', 'auth.permission', 'sessions', 'authtoken.token', 'config.authtoken']

    def handle(self, *args, **options):
        User = get_user_model()
        recipients = list(
            User.objects.filter(is_staff=True).exclude(email='').values_list('email', flat=True)
        )
        if not recipients:
            self.stderr.write(
                'No admin account has an email address on file, so this backup has nowhere '
                'to go. Set one via Change Password / account settings. Skipping.'
            )
            return

        buffer = StringIO()
        call_command('dumpdata', exclude=self.EXCLUDED_MODELS, indent=2, stdout=buffer)
        compressed = gzip.compress(buffer.getvalue().encode('utf-8'))

        timestamp = timezone.now().strftime('%Y%m%d_%H%M%S')
        filename = f'apex_binary_backup_{timestamp}.json.gz'
        size_kb = len(compressed) / 1024

        email = EmailMessage(
            subject=f'Apex Binary: database backup {timestamp}',
            body=(
                f'Automated database backup, generated {timezone.now():%Y-%m-%d %H:%M} '
                f'({settings.TIME_ZONE}).\n\n'
                f'Attached: {filename} ({size_kb:.1f} KB gzipped).\n\n'
                'Full JSON dump (Django dumpdata format), excluding content types, '
                'permissions, sessions, and API auth tokens (all auto-regenerated and/or '
                "sensitive to leak in an email). Uploaded files (course materials, client "
                'logos) are NOT included — see README-DEPLOY.md.\n\n'
                'To restore: gunzip the attachment, then run\n'
                '  python manage.py loaddata <file>.json\n'
                'against a target database with migrations already applied.'
            ),
            from_email=settings.DEFAULT_FROM_EMAIL,
            to=[],
            bcc=recipients,
        )
        email.attach(filename, compressed, 'application/gzip')
        email.send()

        self.stdout.write(self.style.SUCCESS(
            f'Backup emailed to {len(recipients)} admin(s): {filename} ({size_kb:.1f} KB gzipped).'
        ))
