"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import config
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (fail closed) — a deploy that forgets to set this env var gets a
# safe production posture instead of DEBUG=True leaking tracebacks/settings (including
# SECRET_KEY/DATABASE_URL) to the public internet on every unhandled 500. Local dev
# needs DEBUG=True in backend/.env explicitly (see .env.example) — it's not free anymore.
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret! No hardcoded
# fallback here — a committed default would be a known-public secret the moment this
# repo is public, and would be silently used if the real env var were ever missing in
# production. In production (DEBUG=False), a missing SECRET_KEY fails loudly at
# startup instead. In local dev, a fresh, ephemeral key is generated per run so
# nothing crashes — but it means every restart invalidates existing sessions/CSRF
# tokens/password-reset links; set SECRET_KEY in backend/.env for a stable local key.
SECRET_KEY = config('SECRET_KEY', default=None)
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            'SECRET_KEY environment variable is not set. Refusing to start in '
            'production (DEBUG=False) without one - see backend/README-DEPLOY.md.'
        )
    SECRET_KEY = get_random_secret_key()
    print(
        '\n*** WARNING: no SECRET_KEY set - using a random, ephemeral key for this dev '
        'run only. Sessions/CSRF tokens/password-reset links will stop working on the '
        'next restart. Set SECRET_KEY in backend/.env for a stable one. ***\n'
    )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# Trusted origins for unsafe (POST/PUT/etc) requests carrying a session cookie — mainly
# the Django admin login and any session-authenticated request. Token-authenticated API
# calls from the React frontend aren't affected (no session cookie involved). Empty by
# default so local dev (no HTTPS, no custom domain) doesn't need this set at all.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)

# Host-agnostic on purpose (see backend/README-DEPLOY.md) — whichever cloud runs this,
# setting the same env vars is enough, no code change needed. HTTPS is only enforced
# when DEBUG=False, so local dev over plain http:// still works.
if not DEBUG:
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'config',
    'students',
    'trainers',
    'clients',
    'courses',
    'enrollments',
    'attendance',
    'billing',
    'reports',
    'audit',
    'batches',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static files (admin CSS/JS, DRF browsable-API assets) directly
    # from the Django process — no separate static host/CDN needed on a free-tier deploy.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASE_URL (e.g. Neon's Postgres connection string) takes over whenever it's set —
# any host works the same way, just by setting this one env var. Falls back to local
# SQLite so `manage.py runserver`/`test` still work with zero setup.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        ssl_require=config('DATABASE_SSL_REQUIRE', default=True, cast=bool),
    ),
}
# ssl_require above forces sslmode=require, which SQLite's URL scheme doesn't accept —
# only apply it when actually using Postgres (i.e. DATABASE_URL was set).
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].pop('OPTIONS', None)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    # Compressed, cache-busted filenames — collectstatic (run in the deploy build step)
    # writes into STATIC_ROOT, which WhiteNoiseMiddleware then serves.
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Uploaded files (course materials) — local disk. Deliberately not moved to S3/R2 yet:
# free-tier hosts wipe this on redeploy, which is an accepted trade-off for now (see
# backend/README-DEPLOY.md) rather than something worth the added complexity today.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.authentication.AuthTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Applies only to ModelViewSet/ListAPIView `list` actions — custom @action
    # endpoints that build their own Response() are unaffected. 100 comfortably
    # covers every current unfiltered admin list (largest today is ~54
    # enrollments), while capping runaway growth later (Attendance alone is
    # already at ~800 rows, though every current fetch of it is scoped by
    # ?trainer=/?enrollment= so this doesn't change what any page shows today).
    # The frontend api() client unwraps {results: [...]} transparently — see
    # frontend/src/api/client.js — so existing pages don't need to change.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    # Per-client-IP limits on the unauthenticated endpoints most worth guarding against
    # brute-forcing/spamming — see config/throttling.py for the classes that use these.
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'password_reset': '3/min',
        'parent_link': '30/min',
    },
}

# CORS — allow the React dev server during Phase 4
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=lambda v: [s.strip() for s in v.split(',')],
)
CORS_EXPOSE_HEADERS = ['Content-Disposition']

# Email — currently only used for the admin "forgot password" flow (see
# config.views.PasswordResetRequestView). Falls back to printing emails to the
# console instead of crashing when no real credentials are configured yet, so
# local development works before the .env is filled in.
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'no-reply@localhost')
# The "From" address on error emails specifically (see LOGGING/ADMINS below) —
# separate from DEFAULT_FROM_EMAIL since some SMTP providers reject a From address
# that doesn't match the authenticated account.
SERVER_EMAIL = config('SERVER_EMAIL', default=EMAIL_HOST_USER or 'no-reply@localhost')

# Base URL of the frontend — used to build the link inside the password-reset email.
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# How long a password-reset link stays valid, in seconds — enforced by Django's
# default_token_generator (used in PasswordResetConfirmView). Default is 3 days;
# tightened to 15 minutes since these links go out over email.
PASSWORD_RESET_TIMEOUT = 900

# Who gets emailed on an unhandled 500/exception (see LOGGING below) — e.g.
# "Admin One:admin1@example.com,Admin Two:admin2@example.com". Empty by default: Django's
# mail_admins() silently no-ops if ADMINS is empty, so this is safe to leave unset in dev.
ADMINS = config(
    'ADMINS', default='',
    cast=lambda v: [tuple(pair.split(':', 1)) for pair in v.split(',') if ':' in pair],
)

# No external error tracker (Sentry/Rollbar/etc.) is set up yet — on Render, console
# output is lost on every dyno restart/redeploy, so without this an unhandled 500 would
# be invisible unless someone happened to be watching the live log stream at that exact
# moment. mail_admins is Django's built-in fallback: it emails everyone in ADMINS (via
# the EMAIL_BACKEND configured above) with the traceback whenever something logs at
# ERROR level or above through the 'django' logger — which includes every unhandled
# view exception, since Django's exception-handling middleware logs there automatically.
# Only fires when DEBUG=False (RequireDebugFalse), so local dev doesn't get spammed.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'root': {
        'handlers': ['console', 'mail_admins'],
        'level': 'INFO',
    },
    # Explicit and non-propagating so a 'django'-namespaced log (e.g. the
    # exception-handling middleware's 500 log) is handled exactly once here, instead
    # of also bubbling up to root's identical handlers and sending two emails.
    # Everything else (e.g. logger.exception() calls elsewhere in the app) has no
    # specific entry, so it falls through to root's handlers as normal.
    'loggers': {
        'django': {
            'handlers': ['console', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
