# Generated by Django 6.0.7 on 2026-07-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clients', '0003_clientcourserate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='billing.billingcycle')),
            ],
            options={
                'unique_together': {('client', 'cycle')},
            },
        ),
    ]
