# Generated by Django 6.0.7 on 2026-07-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerequest'),
        ('billing', '0002_clientinvoice'),
        ('trainers', '0002_trainer_default_rate_per_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_adjustments', to='billing.billingcycle')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_adjustment', to='attendance.attendance')),
                ('source_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.billingcycle')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_adjustments', to='trainers.trainer')),
            ],
        ),
    ]
