# Generated by Django 6.0.7 on 2026-07-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerequest'),
        ('billing', '0003_payoutadjustment'),
        ('clients', '0005_clientcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_invoice_adjustments', to='billing.billingcycle')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_adjustment', to='attendance.attendance')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_adjustments', to='clients.client')),
                ('source_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.billingcycle')),
            ],
        ),
    ]
