# Generated by Django 6.0.7 on 2026-07-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_clientinvoiceadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoiceadjustment',
            name='trainer_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
