# Generated by Django 6.0.7 on 2026-07-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_clientinvoiceadjustment_trainer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutadjustment',
            name='applied_cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applied_adjustments', to='billing.billingcycle'),
            preserve_default=False,
        ),
    ]
