# Generated by Django 6.0.7 on 2026-07-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_payoutadjustment_applied_cycle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingcycle',
            unique_together={('cycle_start', 'cycle_end')},
        ),
    ]
