# Generated by Django 6.0.7 on 2026-07-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_billingcycle_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b2b_classes', models.IntegerField(default=0)),
                ('b2b_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b2b_trainer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b2c_classes', models.IntegerField(default=0)),
                ('b2c_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('b2c_trainer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshot', to='billing.billingcycle')),
            ],
        ),
    ]
