# Generated by Django 6.0.7 on 2026-07-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerequest'),
        ('billing', '0008_cyclerevenuesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CRevenueAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('trainer_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_b2c_adjustments', to='billing.billingcycle')),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_revenue_adjustment', to='attendance.attendance')),
                ('source_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.billingcycle')),
            ],
        ),
    ]
