# Generated by Django 6.0.7 on 2026-07-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_b2crevenueadjustment'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0003_course_rate_per_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('rate_per_class', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course')),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'course', 'effective_from'], name='billing_rat_content_b02354_idx')],
            },
        ),
    ]
