# Generated by Django 6.0.7 on 2026-08-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_ratehistory'),
        ('clients', '0006_alter_client_rate_per_class_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['status', 'cycle'], name='billing_cli_status_af9b99_idx'),
        ),
    ]
