# Generated by Django 6.0.7 on 2026-08-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_clientinvoice_billing_cli_status_af9b99_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='paid_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
