# Generated by Django 6.0.7 on 2026-07-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_rate_per_class'),
        ('students', '0003_parentsharelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Scratch Programming — July 2026 batch"', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('total_classes', models.IntegerField()),
                ('fee_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('one_time', 'One-time payment'), ('two_installments', 'Two installments'), ('three_installments', 'Three installments'), ('four_installments', 'Four installments')], default='one_time', max_length=20)),
                ('start_date', models.DateField()),
                ('class_time', models.TimeField(blank=True, null=True)),
                ('class_days', models.CharField(blank=True, default='', help_text='Comma-separated day codes, e.g. MON,WED,FRI', max_length=50)),
                ('meet_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=10)),
                ('payout_recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payout_paid', models.BooleanField(default=False)),
                ('payout_paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='courses.course')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='batches.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-joined_date'],
                'unique_together': {('batch', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BatchInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('due_at_sessions', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('batch_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='batches.batchenrollment')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('conducted_by_name', models.CharField(help_text='Trainer or anyone else who took this session', max_length=255)),
                ('topic_covered', models.TextField(blank=True, default='')),
                ('recording_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='batches.batch')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
