# Generated by Django 6.0.7 on 2026-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
        ('trainers', '0002_trainer_default_rate_per_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='batches', to='trainers.trainer'),
        ),
    ]
