# Generated by Django 6.0.7 on 2026-08-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_batch_trainers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='trainers',
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer_names',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
