# Generated by Django 6.0.7 on 2026-08-01 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_remove_batch_trainers_batch_trainer_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='payout_amount',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='payout_paid',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='payout_paid_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='payout_recipient_name',
        ),
        migrations.CreateModel(
            name='BatchPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='batches.batch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
