# Generated by Django 6.0.7 on 2026-08-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_remove_batch_payout_amount_remove_batch_payout_paid_and_more'),
        ('students', '0003_parentsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchenrollment',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='guest_occupation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='guest_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='guest_source',
            field=models.CharField(blank=True, default='', help_text='How they heard about us, e.g. referral, social media, walk-in', max_length=255),
        ),
        migrations.AlterField(
            model_name='batchenrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='students.student'),
        ),
    ]
