# Generated by Django 6.0.7 on 2026-08-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_batchenrollment_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='accepting_enrollments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='refund_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='batchenrollment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
