# Generated by Django 6.0.7 on 2026-08-08 02:46, hand-edited: the autogenerated
# version dropped `paid` and added `paid_status` in one step, which would have
# silently reset every already-paid BatchPayout back to 'pending'. Split into
# add -> copy -> remove so existing paid=True rows land on paid_status='paid'.

from django.db import migrations, models


def copy_paid_to_paid_status(apps, schema_editor):
    BatchPayout = apps.get_model('batches', 'BatchPayout')
    BatchPayout.objects.filter(paid=True).update(paid_status='paid')


def copy_paid_status_to_paid(apps, schema_editor):
    BatchPayout = apps.get_model('batches', 'BatchPayout')
    BatchPayout.objects.filter(paid_status='paid').update(paid=True)


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_batchsession_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchpayout',
            name='paid_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')],
                default='pending', max_length=10,
            ),
        ),
        migrations.RunPython(copy_paid_to_paid_status, copy_paid_status_to_paid),
        migrations.RemoveField(
            model_name='batchpayout',
            name='paid',
        ),
    ]
