# Generated by Django 6.0.7 on 2026-08-08 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_remove_batchpayout_paid_batchpayout_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='fee_per_student',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='batchinstallment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
