# Generated by Django 6.0.7 on 2026-08-08 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0009_alter_batch_fee_per_student_and_more'),
        ('students', '0003_parentsharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='batchenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', True), models.Q(('guest_phone_number', ''), _negated=True)), fields=('batch', 'guest_name', 'guest_phone_number'), name='unique_guest_enrollment_per_batch'),
        ),
    ]
