# Generated by Django 6.0.7 on 2026-08-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0010_alter_batchpayout_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batchenrollment',
            name='unique_guest_enrollment_per_batch',
        ),
        migrations.RemoveField(
            model_name='batchenrollment',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='batchenrollment',
            name='guest_phone_number',
        ),
    ]
