# Generated by Django 6.0.7 on 2026-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='class_days',
            field=models.CharField(blank=True, default='', help_text='Comma-separated day codes, e.g. MON,WED,FRI', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
