# Generated by Django 6.0.7 on 2026-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_paymentplan_paymentinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='refund_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='paid_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
