# Generated by Django 6.0.7 on 2026-08-03 15:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_discount_percent(apps, schema_editor):
    # discount_percent was never stored before this field existed — best-effort
    # reconstruct it from what we do have (total_amount vs. the course's standard
    # price at the classes_total the plan was created for), so an existing plan's
    # first future classes_total edit still reprices with roughly the right discount
    # instead of silently assuming 0%. See services.recalculate_payment_plan().
    PaymentPlan = apps.get_model('enrollments', 'PaymentPlan')
    for plan in PaymentPlan.objects.select_related('enrollment__course').all():
        course = plan.enrollment.course
        classes_total = plan.enrollment.classes_total
        rate = course.rate_per_class
        if not rate or not classes_total:
            continue
        standard_total = rate * classes_total
        if standard_total <= 0:
            continue
        discount = (Decimal('1') - (plan.total_amount / standard_total)) * Decimal('100')
        discount = max(Decimal('0.00'), min(discount, Decimal('15.00')))
        plan.discount_percent = discount.quantize(Decimal('0.01'))
        plan.save(update_fields=['discount_percent'])


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_enrollment_classes_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RunPython(backfill_discount_percent, migrations.RunPython.noop),
    ]
