# Generated by Django 6.0.7 on 2026-08-04 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_rate_per_class_and_more'),
        ('enrollments', '0007_paymentplan_discount_percent'),
        ('students', '0003_parentsharelink'),
        ('trainers', '0003_alter_trainer_default_rate_per_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['trainer', 'status', 'class_time'], name='enrollments_trainer_ba4799_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['paid_status'], name='enrollments_paid_st_bcd747_idx'),
        ),
        migrations.AddIndex(
            model_name='substituteassignment',
            index=models.Index(fields=['substitute_trainer', 'start_date', 'end_date'], name='enrollments_substit_e4a83d_idx'),
        ),
    ]
