# Generated by Django 6.0.7 on 2026-08-09 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_enrollment_enrollments_trainer_ba4799_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='client_rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='trainer_rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
