# Generated by Django 6.0.7 on 2026-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='default_rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Applies to every course unless overridden by a TrainerCourseRate for that course.', max_digits=8, null=True),
        ),
    ]
