# Generated by Django 6.0.7 on 2026-07-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard per-class price for B2C students. Used to default the total course fee on a B2C enrollment.', max_digits=8, null=True),
        ),
    ]
