# Generated by Django 6.0.7 on 2026-08-01 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_rate_per_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard per-class price for B2C students. Used to default the total course fee on a B2C enrollment.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_classes',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
