# Generated by Django 6.0.7 on 2026-08-08 14:13

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_rate_per_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(upload_to='course_materials/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), courses.models.validate_course_material_size]),
        ),
    ]
