# Generated by Django 6.0.7 on 2026-07-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('topic_covered', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='enrollments.enrollment')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance', to='trainers.trainer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
