# Generated by Django 6.0.7 on 2026-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerequest'),
        ('enrollments', '0006_alter_enrollment_classes_completed_and_more'),
        ('trainers', '0003_alter_trainer_default_rate_per_class_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('enrollment', 'date'), name='unique_attendance_per_enrollment_date'),
        ),
    ]
