# Generated by Django 6.0.7 on 2026-08-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_unique_attendance_per_enrollment_date'),
        ('enrollments', '0007_paymentplan_discount_percent'),
        ('trainers', '0003_alter_trainer_default_rate_per_class_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'date'], name='attendance__status_a2ceef_idx'),
        ),
    ]
