# Generated by Django 6.0.7 on 2026-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_attendance__status_a2ceef_idx'),
        ('enrollments', '0009_enrollment_client_rate_per_class_and_more'),
        ('trainers', '0003_alter_trainer_default_rate_per_class_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_enrollment_date',
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='request_type',
            field=models.CharField(choices=[('late_entry', 'Late entry (closed billing cycle)'), ('duplicate_day', 'Second class same day')], default='late_entry', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['enrollment', 'date'], name='attendance__enrollm_9957ca_idx'),
        ),
    ]
