# Generated by Django 6.0.7 on 2026-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount this client pays us per class attended by their students.', max_digits=8, null=True),
        ),
    ]
