# Generated by Django 6.0.7 on 2026-07-24 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_rate_per_class'),
        ('courses', '0002_coursematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCourseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_class', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_rates', to='clients.client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rates', to='courses.course')),
            ],
            options={
                'unique_together': {('client', 'course')},
            },
        ),
    ]
