# Generated by Django 6.0.7 on 2026-08-01 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rate_per_class',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount this client pays us per class attended by their students.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clientcourserate',
            name='rate_per_class',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
