# Generated by Django 6.0.7 on 2026-08-10 07:54

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_rate_per_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='client_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp']), clients.models.validate_logo_size]),
        ),
        migrations.AddField(
            model_name='client',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='e.g. "Excellence in Coding Education".', max_length=255),
        ),
    ]
